### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by dschippe** [ariel-waisman/LabelsToROIs#1]
Hi,

I went ahead and put the plugin into the imageJ plugin folder and when I try to run it I get the error below.  Any idea what I am doing wrong?

Thanks,
David 

SyntaxError: ("mismatched input ',' expecting COLON", ('<string>', 309, 73, "                       with open(full_table_path, 'a') as full_table_file, open(path_to_multiple_Tables, 'r') as current_table:\n"))

**Comment by ariel-waisman** [comment]
Hi David! Thanks a lot for your interest in the project. 
The problem seems to be that you are using an older version of Jython. Is it possible for you to update your FIJI/ImageJ version and try again?

Cheers, 
Ari

**Comment by gunjan-sh** [comment]
Hi, 
I am having a similar issue. Not able to load the plugin. I followed the steps and also updated the ImageJ app with latest version on Mac but I see the following error:

SyntaxError: ("mismatched input ',' expecting COLON", ('<string>', 311, 73, " with open(full_table_path, 'a') as full_table_file, open(path_to_multiple_Tables, 'r') as current_table:\n")) 

Any pointers on how I can fix this ?

Thanks.
Gunjan

**Comment by ariel-waisman** [comment]
Hi Gunjan, 
Are you using Fiji or ImageJ? That error appears specific to ImageJ users, but should not occur in FIJI, so maybe you could try that. 

Similar issue here:
https://github.com/ariel-waisman/LabelsToROIs/issues/3

Hope that helps! 
Best
Ariel

**Comment by gunjan-sh** [comment]
Hi Ariel, 
Thanks for your reply and suggestions. I was using Basic ImageJ earlier. I installed the plugin now with FIJI and its loading. 
After loading the plugin, I followed the next steps from your https://labelstorois.github.io/ page to generate ROIs from  Labeled images, using some original and labeled tif images after choosing Single Image option but I am getting following Error : 

Reading IFDs
Populating metadata
Populating OME metadata

Exception in thread "AWT-EventQueue-0" Traceback (most recent call last):
  File "Labels_To_Rois.py", line 495, in f2_clic_next
AttributeError: 'NoneType' object has no attribute 'show'

Is there anything I am missing ? Or doing wrong ?

**Comment by dapsoc** [comment]
Hi, 

After loading the images in the plugin/image j, I also have the error:
Reading IFDs
Populating metadata
Populating OME metadata

Exception in thread "AWT-EventQueue-0" Traceback (most recent call last):
File "Labels_To_Rois.py", line 495, in f2_clic_next
AttributeError: 'NoneType' object has no attribute 'show'

Is there any way to solve this?

Thanks in advance!

**Comment by ariel-waisman** [comment]
Hi! 

Are you using an "original image" that is actually a multichannel TIFF file? As it is right now, the plugin for Single Image only works with single-channel images as original images, or else you'll get that error. I'll try to fix it in the future. In the meantime, you can always reload the generated ROIs in the multichannel image after tuning the ROIs. Hope that helps, good luck!!
